name: SemVer

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create Release
        id: release-action
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.ref.name }}
          allowUpdates: true
          draft: true
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          body: Changelog Contents
          token: ${{ github.token }}
          # tag: ${{ steps.semver.outputs.next }}
